# Site settings
title: Douglas Qian
description: Yo. Welcome to my crib.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://douglasqian.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Douglas Qian
user_description:
user_title: CMU Comp Bio 19'
email: douglaszqian@gmail.com
twitter_username: douglasqian
github_username:  douglasqian
calendar_link: https://calendar.google.com/calendar?cid=ZG91Z2xhc3pxaWFuQGdtYWlsLmNvbQ
youtube_channel:  https://www.youtube.com/channel/UCmBIel8NV2fan9xwl3m5deg
linkedin_username:  douglas-qian
medium_username:  doug.the.rug

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
